### ISSUE TITLE
Remove the nasty button selection!!! 

### ISSUE THREAD

**Issue by ErginDapaj** [discordlist-gg/beta-issues#192]
### Description
Only happens in mobile, I remember having the same bug and I solved it with a quick solution.

### Pictures
https://media.discordapp.net/attachments/736932833863663646/976400932592029716/XRecorder_18052022_102730.mp4
### Solution
```CSS
/* This will get rid of the nasty select on mobile :) */
html {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
